launcher:
  app: ProfileEnabledApp

profiles:
  - name: 1
    model: exclude
    matching: satisfy-all
    tags:
      - a
      - b
  - name: 2
    model: include
    matching: satisfy-any
    tags:
      - e
      - f